version: '3.8'

services:
  db:
    container_name: postgres_db
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
  web:
    container_name: main
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
     - 8000:8000
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local