# Generated by Django 4.2.1 on 2023-05-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_hotelroommodel_hotel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelroommodel",
            name="hotel",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_room",
                to="api.hotelmodel",
            ),
            preserve_default=False,
        ),
    ]
